name: color_merge
description: "A lightweight Flutter package that provides color merging utilities for blending colors seamlessly."
version: 1.0.1
homepage: https://github.com/hesham04Dev/color_merge

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

screenshots:
  - description: Color Merge logo.
    path: screenshots/logo.png


